src/beans/Contribution.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class Contribution implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private int user_id;
    private String title;
    private String category;
    private String text;
    private Date created_date;
    private Date updated_date;

	public int getId() {
		return id;
	}
    public void setId(int id) {
    	this.id = id;
    }
    public int getUserId() {
		return user_id;
	}
	public void setUserId(int user_id) {
		this.user_id = user_id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public Date getCreatedDate() {
		return created_date;
	}
	public void setCreatedDate(Date created_date) {
		this.created_date = created_date;
	}
	public Date getUpdatedDate() {
		return updated_date;
	}
	public void setUpdatedDate(Date updated_date) {
		this.updated_date = updated_date;
	}

}

src/beans/User.java
package beans;

import java.io.Serializable;


public class User implements Serializable {
	private static final long serialVersionUID = 1L;

	private int id;
	private String  login_id;
	private int branch_id;
	private int department_id;
	private boolean isStopped;
	private String password;
	private String name;

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id =id;
	}
	public String getLoginId() {
		return login_id;
	}
	public void setLoginId(String login_id) {
		this.login_id =login_id;
	}
	public int getBranchId() {
		return branch_id;
	}
	public void setBranchId(int branch_id) {
		this.branch_id = branch_id;
	}
	public int getDepartmentId() {
		return department_id;
	}
	public void setDepartmentId(int department_id) {
		this.department_id = department_id;
	}
	public String  getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public boolean isStopped() {
		return isStopped;
	}
	public void setStopped(boolean isStopped) {
		this.isStopped = isStopped;
	}
}

src/controller/HomeServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Search;
import beans.User;
import beans.UserComment;
import beans.UserContribution;
import service.CommentService;
import service.ContributionService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class HomeServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException{

		//ログインユーザー情報取得
		HttpSession session = request.getSession();
		User user = (User) session.getAttribute("loginUser");
		request.setAttribute("loginUser", user);

		//検索してない場合の表示
		List<UserContribution> contributions = new ContributionService().getContribution();
		request.setAttribute("contribution", contributions);
		List<UserComment> comments = new CommentService().getComment();
		request.setAttribute("comment", comments);

		request.getRequestDispatcher("home.jsp").forward(request, response);
	}
	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.setCharacterEncoding("UTF-8");

		boolean from = true;
		boolean to = true;
		Search search = setInputSearch(request);

		//検索欄に入力がない場合
		if (search.getCategory() == null && search.getFrom() == null && search.getTo() == null) {
			List<UserContribution> contributions = new ContributionService().getContribution();
			request.setAttribute("contribution", contributions);
			List<UserComment> comments = new CommentService().getComment();
			request.setAttribute("comment", comments);

			request.getRequestDispatcher("home.jsp").forward(request, response);
		} else {
			if (!StringUtils.isEmpty(search.getCategory())) {
				request.setAttribute("editCategory", search.getCategory());
			}
			if (!StringUtils.isEmpty(search.getFrom())) {
				request.setAttribute("editFrom", search.getFrom());
			}
			if (!StringUtils.isEmpty(search.getTo())) {
				request.setAttribute("editTo", search.getTo());
			}
			//該当の投稿をセット
			List<UserContribution> contributions = new ContributionService().search(search);
			List<UserComment> comments = new CommentService().getComment();
			request.setAttribute("contribution", contributions);
			request.setAttribute("comment", comments);

			//検索結果がない場合
			if (contributions == null) {
				List<String> messages = new ArrayList<String>();
				messages.add("検索結果はありません");
				request.setAttribute("errorMessages", messages);
			}
			request.getRequestDispatcher("home.jsp").forward(request, response);
		}
	}


	private Search setInputSearch(HttpServletRequest request) {
		Search search = new Search();
		search.setCategory(request.getParameter("category"));
		search.setFrom(request.getParameter("from"));
		search.setTo(request.getParameter("to"));
		return search;
	}
}

src/controller/LoginServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.BooleanUtils;

import beans.User;
import service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("login.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		String login_id = request.getParameter("login_id");
		String password = request.getParameter("password");

		LoginService loginService = new LoginService();
		User user = loginService.login(login_id, password);
		HttpSession session = request.getSession();

		if (user != null &&(BooleanUtils.toInteger (user.isStopped()) == 0)){
			session.setAttribute("loginUser", user);
			response.sendRedirect("./");
		} else {
			List<String> messages = new ArrayList<String>();
			messages.add("ログインに失敗しました。");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("login");
		}
	}
}

src/controller/SignUpServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.BranchService;
import service.DepartmentService;
import service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		HttpSession session = request.getSession();
		User user = (User) session.getAttribute("loginUser");

		if(user == null) {
			List<String> messages = new ArrayList<String>();
			messages.add("ログインしてください!");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("login");
		}else if(user.getDepartmentId() != 1)  {
			List<String> messages = new ArrayList<String>();
			messages.add("権限がないためアクセスできません!");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("./");
		}else {
			Map<String, String> branchMap = new BranchService().findAll();
			Map<String, String> departmentMap = new DepartmentService().findAll();
			session.setAttribute("branch", branchMap);
			session.setAttribute("department", departmentMap);
			request.getRequestDispatcher("signup.jsp").forward(request, response);
		}
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		List<String> messages = new ArrayList<String>();

		HttpSession session = request.getSession();
		User user = new User();
		if (isValid(request, messages) == true) {

			user.setLoginId(request.getParameter("login_id"));
			user.setBranchId(Integer.parseInt(request.getParameter("branch_id")));
			user.setDepartmentId(Integer.parseInt(request.getParameter("department_id")));
			user.setName(request.getParameter("name"));
			user.setPassword(request.getParameter("password"));

			new UserService().register(user);
			session.removeAttribute("branch");
			session.removeAttribute("department");
			response.sendRedirect("userManagement");
		} else {
			session.setAttribute("errorMessages", messages);
			request.setAttribute("editUser", user);
			response.sendRedirect("signup");
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {
		String loginId = request.getParameter("login_id");
		String name =request.getParameter("name");
		String password = request.getParameter("password");
		String passwordConfirm = request.getParameter("password_confirm");
		boolean passwordFlag = false;
		boolean passwordConfirmFlag = false;

		if (StringUtils.isEmpty(loginId) == true) {
			messages.add("IDを入力してください!");
		}else if (!loginId.matches("[a-zA-Z0-9]{6,20}")) {
			messages.add("ログインIDは半角英数字6文字以上20文字以下で入力してください!");
		}
		if (StringUtils.isEmpty(name) == true) {
			messages.add("名前を入力してください!");
		}else if (name.length() > 10) {
			messages.add("名前は10文字以下で入力してください!");
		}
		if (StringUtils.isEmpty(password) == true) {
			messages.add("passを入力してください!");
		}else if (!password.matches("[ -~]{6,255}")) {
			messages.add("パスワードは半角文字6文字以上255文字以下で入力してください!");
		} else {
			passwordFlag = true;
		}
		if (StringUtils.isEmpty(passwordConfirm)) {
			messages.add("パスワード(確認用)を入力してください!");
		} else if (!passwordConfirm.matches("[ -~]{6,255}")) {
			messages.add("パスワード(確認用)は半角文字6文字以上255文字以下で入力してください!");
		} else {
			passwordConfirmFlag = true;
		}
		if (passwordFlag && passwordConfirmFlag) {
			if (!password.equals(passwordConfirm)) {
				messages.add("パスワードとパスワード(確認用)の値が不一致です!");
			}
		}

		if( messages.size() == 0) {
			return true;
		}else {
			return false;
		}

	}

}

src/controller/UserEditingServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.BranchService;
import service.DepartmentService;
import service.UserService;

@WebServlet(urlPatterns = { "/userediting" })
public class UserEditingServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		HttpSession session = request.getSession();
		String id = request.getParameter("id");
		User user = (User) session.getAttribute("loginUser");

		if(user == null) {
			List<String> messages = new ArrayList<String>();
			messages.add("ログインしてください!");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("login");
		}else if(user.getDepartmentId() != 1) {
			List<String> messages = new ArrayList<String>();
			messages.add("権限がないためアクセスできません!");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("./");
		}else {
			Map<String, String> branchMap = new BranchService().findAll();
			Map<String, String> departmentMap = new DepartmentService().findAll();
			session.setAttribute("branch", branchMap);
			session.setAttribute("department", departmentMap);

			int userId = 0;
			userId = Integer.parseInt(id);
			User users = new UserService().getUser(userId);
			session.setAttribute("userId", id);
			request.setAttribute("editUser", users);
			request.getRequestDispatcher("userediting.jsp").forward(request, response);
		}
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
		HttpSession session = request.getSession();
		List<String> messages = new ArrayList<String>();
		User user = setInputUser(request);
		UserService userService = new UserService();

		if (isValid(request, messages)) {


			userService.update(user);
			session.removeAttribute("branch");
			session.removeAttribute("department");
			session.removeAttribute("userId");
			response.sendRedirect("userManagement");
		} else {
			request.setAttribute("errorMessages", messages);
			request.setAttribute("editUser", user);
			request.getRequestDispatcher("userediting.jsp").forward(request, response);
		}
	}

	private User setInputUser(HttpServletRequest request) {

		User user = new User();
		user.setId(Integer.parseInt(request.getParameter("id")));
		user.setLoginId(request.getParameter("login_id"));
		user.setPassword(request.getParameter("password"));
		user.setName(request.getParameter("name"));
		user.setBranchId(Integer.parseInt(request.getParameter("branch_id")));
		user.setDepartmentId(Integer.parseInt(request.getParameter("department_id")));

		return user;
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {

		String loginId = request.getParameter("login_id");
		String password = request.getParameter("password");
		String passwordConfirm = request.getParameter("password_confirm");
		String name = request.getParameter("name");
		boolean passwordFlag = false;
		boolean passwordConfirmFlag = false;

		if (StringUtils.isEmpty(loginId)) {
			messages.add("ログインIDを入力してください!");
		} else if (!loginId.matches("[a-zA-Z0-9]{6,20}")) {
			messages.add("ログインIDは半角英数字6文字以上20文字以下で入力してください!");
		}
		if (!StringUtils.isEmpty(password)) {
			if (!password.matches("[ -~]{6,255}")) {
				messages.add("パスワードは半角文字6文字以上255文字以下で入力してください!");
			} else {
				passwordFlag = true;
			}
		}
		if (passwordFlag) {
			if (StringUtils.isEmpty(passwordConfirm)) {
				messages.add("パスワード(確認用)を入力してください!");
			} else if (!passwordConfirm.matches("[ -~]{6,255}")) {
				messages.add("パスワード(確認用)は半角文字6文字以上255文字以下で入力してください!");
			} else {
				passwordConfirmFlag = true;
			}
		} else {
			if (!StringUtils.isEmpty(passwordConfirm)) {
				messages.add("パスワードを入力してください!");
				if (!passwordConfirm.matches("[ -~]{6,255}")) {
					messages.add("パスワード(確認用)は半角文字6文字以上255文字以下で入力してください!");
				}
			}
		}
		if (passwordFlag && passwordConfirmFlag) {
			if (!password.equals(passwordConfirm)) {
				messages.add("パスワードとパスワード(確認用)の値が不一致です!");
			}
		}
		if (StringUtils.isEmpty(name)) {
			messages.add("名前を入力してください!");
		} else if (name.length() > 10) {
			messages.add("名前は10文字以下で入力してください!");
		}
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
}

src/controller/UserManagementServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.ComplementUser;
import beans.User;
import service.UserService;

@WebServlet(urlPatterns = { "/userManagement" })
public class UserManagementServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;



	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		HttpSession session = request.getSession();
		User user = (User) session.getAttribute("loginUser");

		if(user == null) {
			List<String> messages = new ArrayList<String>();
			messages.add("ログインしてください!");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("login");
		}else if(user.getDepartmentId() != 1) {
			List<String> messages = new ArrayList<String>();
			messages.add("権限がないためアクセスできません!");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("./");
		}else {
			//一覧表示
			List<ComplementUser> userList = new UserService().getAllComplementUser();
			request.setAttribute("userList", userList);
			request.getRequestDispatcher("usermanagement.jsp").forward(request, response);
		}
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
	}
}

WebContent/contribution.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>新規投稿</title>
<style>
body {
	background: #CCCCCC;
}

h1 {
	text-align: center;
	font-family:'SimSun',monospace;
}
.errorMessages{
color: #FF0000;
}
ul li {
	list-style: none;
}
textarea {
	resize: none;
}

h5 {
	text-align: right;
	margin-right: 50px;
}
p {
	position: absolute;
	top: 0%;
	right: 10%;
}
</style>
</head>
<body>
	<h1>新規投稿</h1>
<div class="main-contents">
		<c:if test="${ not empty errorMessages }">
	<div class="errorMessages">
		<ul class="error">
			<c:forEach items="${errorMessages}" var="message">
				<li class="validate"> <c:out value="${message}" /></li>
			</c:forEach>
		</ul>
	</div>
	<c:remove var="errorMessages" scope="session"/>
</c:if>

		<form action="newContribution" method="post">
		<label for="title">件名</label><br /> <input name="title"  id="title" /><br />
		 <label for="category">カテゴリ</label><br /> <input name="category"  id="category" /><br />
		<label for="text">本文</label><br /> <textarea name="text" cols="100" rows="10" class="tweet-box"></textarea>
		<br /> <label>投稿者：</label>${loginUser.name} 様<br />
		 <input type="submit" value="投稿">
			<p> <a href="./">戻る</a></p>
	</form>
	<h5>
		<div class="copyright">Copyright(c)Eguchi_Naoki</div>
	</h5>
	</div>
</body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ログイン</title>
<style>
body {
	background: #CCCCCC;
}

h1 {
	text-align: center;
	margin-left: 40px;
	font-family:'SimSun',monospace;
}
.errorMessages{
color: #FF0000;
}

ul li {
	list-style: none;
	text-align: center;
}

h5 {
	text-align: right;
	margin-right: 50px;
}

p {
	position: absolute;
	top: 0%;
	right: 10%;
}
</style>
</head>
<body>
	<h1>ログイン</h1>
	<div class="main-contents">

		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>

		<form action="login" method="post">
			<br />
			<ul>
				<li><label for="login_id">ログインID</label><br /> <input
					name="login_id" id="login_id" /></li>

				<li><label for="password">パスワード</label><br /> <input
					name="password" type="password" id="password" /></li>

				<li><input type="submit" value="ログイン" /></li>
				<p>
					<a href="./">戻る</a>
				</p>
			</ul>
		</form>
		<h5>
			<div class="copyright">Copyright(c)Eguchi_Naoki</div>
		</h5>
	</div>
</body>
</html>

WebContent/signup.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ユーザー登録</title>
<style>
h1 {
	text-align: center;
	font-family:'SimSun',monospace;
}
.errorMessages{
color: #FF0000;
}
body {
	background: #CCCCCC;
}

ul li {
	list-style: none;
}

ul {
	width: 230px;
	margin: 0 auto;
}

label {
	margin-right: 10px;
	width: 130px;
	float: left;
}
h5{
text-align:right;
margin-right:50px;
}
p{
position: absolute;
	top: 0%;
	right: 10%;
}
</style>
</head>
<body>
	<h1>ユーザー登録</h1>
	<div class="main-contents">
		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><nobr><c:out value="${message}" /></nobr>
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>
		<form action="signup" method="post">
			<ul>
				<li><label for="name">名前</label><br /> <input name="name"
					id="name"  /></li>
				<li><label for="login_id">ID</label><br /> <input name="login_id"
					id="login_id"  /></li>
					<li><label for="branch_id" >支店名</label><br />
					<select size=1 style="width:175px;" name="branch_id" >
				<c:forEach var="branch" items="${branch}">
					<option value="<c:out value="${branch.key}" />"
					<c:if test="${editUser.branchId == branch.key}">selected</c:if>>
					<c:out value="${branch.value}" />
					</option>
				</c:forEach>
				</select></li>
				<li><label for="department_id" >部署・役職</label><br />
				<select size=1 style="width:175px;" name="department_id" >
				<c:forEach items="${department}" var="department">
					<option value="<c:out value="${department.key}" />" <c:if test="${editUser.departmentId == department.key}">selected</c:if>><c:out value="${department.value}" /></option>
				</c:forEach>
				</select>
				<li><label for="password">pass</label> <br /> <input
					name="password" type="password" id="password"  /></li>
					<li><label for="password_confirm">pass（確認用）</label> <br /> <input
					name="password_confirm" type="password" id="password_confirm"  /></li>
				<ul>
				<li><input type="submit" value="登録" /> <br /></li>
				<p><a href="userManagement">戻る</a></p>
				</ul>
				</ul>
		</form>
		<h5><div class="copyright">Copyright(c)Eguchi_Naok</div></h5>
	</div>
</body>
</html>

WebContent/userediting.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ユーザー情報編集</title>
<style>
body {
	background: #CCCCCC;
}

.errorMessages {
	color: #FF0000;
}

label {
	margin-right: 30px;
	width: 100px;
	float: left;
}

h1 {
	text-align: center;
	font-family: 'SimSun', monospace;
}

p {
	position: absolute;
	top: 0%;
	right: 10%;
}

h5 {
	text-align: right;
	margin-right: 50px
}

ul {
	width: 500px;
	margin: 0 auto;
}

ul li {
	list-style: none;
}
</style>
</head>
<body>
	<h1>ユーザー情報編集</h1>
	<div class="container">
		<div class="row">
			<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul class="error">
						<c:forEach items="${errorMessages}" var="message">
							<li class="validate"><c:out value="${message}" /></li>
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session" />
			</c:if>
			<p>
				<a href="userManagement">戻る</a>
			</p>
			<form action="userediting" method="post">
				<ul>
					<li><label for="login_id">ログインID</label> <input id="login_id"
						name="login_id" value="${editUser.loginId}" /></li>

					<li><label for="name">名前</label> <input id="name" name="name"
						value="${editUser.name}" /></li>

					<li><label for="branch_id">支店名</label> <select size=1
						style="width: 175px;" name="branch_id">
							<c:forEach var="branch" items="${branch}">
								<option value="${branch.key}"
									<c:if test="${editUser.branchId == branch.key}">selected</c:if>>
									${branch.value}</option>
							</c:forEach>
					</select></li>

					<li><label for="department_id">部署・役職</label> <select size=1
						style="width: 175px;" name="department_id">
							<c:forEach var="department" items="${department}">
								<option value="${department.key}"
									<c:if test="${editUser.departmentId == department.key}">selected</c:if>>${department.value}</option>
							</c:forEach>
					</select></li>

					<li><label for="password">パスワード</label> <input id="password"
						name="password" type="password" /></li>

					<li><label for="password_confirm"><nobr>パスワード(確認)</nobr></label>
						<input id="password_confirm" name="password_confirm"
						type="password" /></li>

					<input type="hidden" name="id" value="${userId}" />
					<li><input type="submit" value="登録" /></li>
				</ul>
			</form>
		</div>
	</div>
	<h5>
		<div class="copylight">Copyright(c)Eguchi_Naoki</div>
	</h5>
</body>
</html>